#!/usr/bin/env php
<?php

/**
 * Simply require console entry point, framework will take care of things.
 */
define('__ROOT__', dirname(__FILE__));
require_once __ROOT__ . "/vendor/pckg/framework/src/console.php";